### ISSUE TITLE
能否解释一下“语句组”和“set语句单位”

### ISSUE THREAD

**Issue by hozuki** [Bilibili/bas#1]
不明白这句话的意思：

> 并行语句用大括号包围后，成为一个set语句单位。

未写明 `set` 嵌套的文法。猜测如下：

```plain
SetExpr
  : SequentialSetExpr
  | SetExprGroup
```

形如：

```plain
set { ... }
  then {
    set { ... }
      then set { ... }
    set { ... }
  }
  then set { ... }
```

**Comment by DIYgod** [comment]
- 语句组类似这样，理论上跟直接写并行语句效果上没有区别（刚才试了下好像有 bug

```js
{
    set t {
        x = 20%
    } 1s
    set t {
        alpha = 0
    } 1s
}
```

- set 不支持嵌套，那条语法的意思是 SetExpr 有这三种

```
SetExpr then SetExpr
```

```
{ SetExpr+ }
```

```
set id {
    (id = (value_expr | [value_expr, string]))*
} time_expr (, string)?
```

**Comment by hozuki** [comment]
呃，我漏看了一行 `{ SetExpr+ }` 这个。

我原来想的是， `set` 没有层级的话语句组意义何在。现在看来是将并行转为串行的类似 `WaitForMultipleObjects` 的东西。

好像没bug？[测试](https://github.com/hozuki/sebas/blob/a9e182dcdb3b4c68e786dfaee0b5bd60ab960141/tests/specs/parsing/set_stmt/set_stmt-tests.js#L85-L95)能通过。
