### ISSUE TITLE
可以通过”插值类型“来给弹幕设置任意CSS样式

### ISSUE THREAD

**Issue by zvrh** [Bilibili/bas#10]
如下面的代码：
```
def path t { }
set t { } 500s, "linear;background-image:url(https://i.loli.net/2018/01/27/5a6b91ea46d55.gif)"
```

**Comment by jabbany** [comment]
233333。。。这种bug也有。感觉都快知道怎么实现的了
<____<

应该开一个 Vulnerability 的 label。。。

**Comment by DIYgod** [comment]
![](https://imgur.com/YarF4ik.png)

**Comment by hozuki** [comment]
所以加[测试](https://github.com/hozuki/sebas/tree/master/tests/specs/parsing)是很重要的。XD

**Comment by DIYgod** [comment]
试验室里的修好啦
