### ISSUE TITLE
将弹幕的ID设为hasOwnProperty可以让其他BAS弹幕失效

### ISSUE THREAD

**Issue by xmcp** [Bilibili/bas#12]
考虑这样一条弹幕：
```
def text hasOwnProperty {
    content = "foo"
}
```
和预想的一样，代码在 `t.def2set.hasOwnProperty(e)` 这行崩了。

代码崩了之后，不仅这条BAS弹幕无法显示，视频中的其他BAS弹幕也跟着一起挂掉了。

**Comment by DIYgod** [comment]
学到了，学到了！

**Comment by hozuki** [comment]
考虑到ES5的普及度，用个Map都是可以的

**Comment by DIYgod** [comment]
试验室里的修好啦，线上要等播放器发版
