### ISSUE TITLE
跳转av视频的按钮发不出来

### ISSUE THREAD

**Issue by oOTnTOo** [Bilibili/bas#19]
跳转av视频的按钮发不出来，无论测试也好，直接发送也好，就是闪烁一下随即消失

**Comment by zhangpeng96** [comment]
> 跳转av视频的按钮发不出来，无论测试也好，直接发送也好，就是闪烁一下随即消失

官方给出的demo和试验室代码只写了`button`的定义，需要`set`后才能使用。另外官方给出的代码中定义时长`duration`无效，删除后在`set`后定义时长即可。

```actionscript
def button c {
    text = "av1714157"
    x = 35%
    y = 45%
    fontSize = 5%
    textColor = 0xffffff
    fillColor = 0x80D8FF
    target = av {
        av = 1714157
        page = 1
        time = 20s
    }
}
set c{
} 10s
```
还有个问题是链接到指定分p无效。BAS的跳转分p，比如P5，是`index_5.html`，而如今b站的分p URL是`?p=5`，这个问题一起反馈给官方吧

**Comment by oOTnTOo** [comment]
> > 跳转av视频的按钮发不出来，无论测试也好，直接发送也好，就是闪烁一下随即消失
> 
> 官方给出的demo和试验室代码只写了`button`的定义，需要`set`后才能使用。另外官方给出的代码中定义时长`duration`无效，删除后在`set`后定义时长即可。
> 
> ```actionscript-3
> def button c {
>     text = "av1714157"
>     x = 35%
>     y = 45%
>     fontSize = 5%
>     textColor = 0xffffff
>     fillColor = 0x80D8FF
>     target = av {
>         av = 1714157
>         page = 1
>         time = 20s
>     }
> }
> set c{
> } 10s
> ```
> 
> 还有个问题是链接到指定分p无效。BAS的跳转分p，比如P5，是`index_5.html`，而如今b站的分p URL是`?p=5`，这个问题一起反馈给官方吧

哦，我set语法用错了……谢谢

**Comment by zhangpeng96** [comment]
> > > 跳转av视频的按钮发不出来，无论测试也好，直接发送也好，就是闪烁一下随即消失
> > 
> > 
> > 官方给出的demo和试验室代码只写了`button`的定义，需要`set`后才能使用。另外官方给出的代码中定义时长`duration`无效，删除后在`set`后定义时长即可。
> > ```
> > def button c {
> >     text = "av1714157"
> >     x = 35%
> >     y = 45%
> >     fontSize = 5%
> >     textColor = 0xffffff
> >     fillColor = 0x80D8FF
> >     target = av {
> >         av = 1714157
> >         page = 1
> >         time = 20s
> >     }
> > }
> > set c{
> > } 10s
> > ```
> > 
> > 
> > 还有个问题是链接到指定分p无效。BAS的跳转分p，比如P5，是`index_5.html`，而如今b站的分p URL是`?p=5`，这个问题一起反馈给官方吧
> 
> 哦，我set语法用错了……谢谢

BAS现在在手机客户端还都没法用吧 sad...
