### ISSUE TITLE
不能绘图有点可惜啊

### ISSUE THREAD

**Issue by jabbany** [Bilibili/bas#2]
以前的代码弹幕系统可以通过过程式语法绘图。
新的是不支持这种绘图？感觉有点可惜。

不过既然是新的语法，能有定义型的矢量图语法大概会很不错。感觉可以借鉴SVG。

**Comment by DIYgod** [comment]
后续有支持矢量图形（svg）的计划

**Comment by DIYgod** [comment]
新增 [path 对象](https://github.com/Bilibili/bas/tree/master/docs#path-对象)，可以使用 svg 路径
