### ISSUE TITLE
parent字段的标注是用字符串的意思么?

### ISSUE THREAD

**Issue by jabbany** [Bilibili/bas#3]
看了文档 `parent = 't'` 部分看起来是给传递字符串而不是对象引用？是这样的设计么？还是说单引号有根据名字dereference object的效果？

**Comment by DIYgod** [comment]
应该是双引号，已修复https://github.com/Bilibili/bas/commit/202854a679bcae3edfa90d1f7e41b801cda900f6

parent 的类型是字符串，即父元素的名字
