### ISSUE TITLE
界面元素的生命周期

### ISSUE THREAD

**Issue by hozuki** [Bilibili/bas#7]
比如我定义一个元素 `a`：

1. 是否可以在之后的弹幕中访问 `a`？
2. 如果能，`a` 会随着生命周期而自动销毁吗？而且如果在其他的弹幕中控制一个可渐变的属性，先后赋值的行为怎么确定？沿用“如果多次出现，以最后一次为准”吗？（这不是同一个弹幕中的 `set`，而是跨弹幕的。）
3. 如果不会自动销毁而且这个对象未在任何 `set` 中出现（未应用过渐变所以无法计算生命周期），是否会提供手动销毁的功能？那么如果出现过，生命周期以谁为准？
4. 播放跳转到（预计的）渐变过程中的时候，会像传统播放器那样忽略元素的创建，还是完全重新计算元素状态？

**Comment by DIYgod** [comment]
1. `a`消失之后生命周期就结束，无法访问到
1. 不同弹幕之间互相隔离，无法跨弹幕控制
1. 未在任何 `set` 中出现会默认停留 4s，相当于 `set name {} 4s`
1. 重新计算元素状态

**Comment by DIYgod** [comment]
目前提供了一个 duration 属性，生命周期计算优先级为：duration 属性 > 动画时间 > 默认4s
